### ISSUE TITLE
Visual Improvements I

### ISSUE THREAD

**Issue by Frankbbg** [Knguyen-dev/SDEV-265-Group-4#26]
# Issue: Visual Improvements I

## Description
These improvements outline the first set of visual changes made to the app to make it more user-friendly and more attractive to the eye.

## Changes
1. Creating a simpler settings page to make things more intuitive for users. (Suggestion by @NukeTheDev and I)
    - The settings will be a single slide bar and the style text box from before.
        - The slide bar will have 3 possible configurations: Creative, Balanced, and Focused. Each slider will be a preset for advanced changes.
    - An advanced settings button that allows the user to access the advanced settings like normal

2. Compress the Geometry on the app (Suggestion by @NukeTheDev and I)
    - The buttons and UI features are very much spread out and too spread out. Compressing UI elements to be closer together would greatly benefit the overall look of the app

3. Navigation bar on the side. Doing this would free up space in the top area. (Suggestion by @NukeTheDev)
    - Optional extra feature: make the side bar collapsible to conserve space

4. Make the navigation bar have a dark green glass gradient (Suggestion by @NukeTheDev)

5. Add stylized bubbles for the story creation area to improve the look of the story creation window (Suggestion by me)

6. Give the user the option to toggle a dark mode version of the app in settings.

## Discussion
If anyone wants to provide feedback regarding these proposed changes, you can do it during our meetings. If anyone thinks this will be too much to handle with the given time, please feel free to share your thoughts on that during team meetings as well.

**Comment by Knguyen-dev** [comment]
I feel like dark mode will definitely be possible.

**Comment by Knguyen-dev** [comment]
I'll go and work on dark mode thing or try to.

**Comment by CPhillips-dev** [comment]
#38 Pull request has implemented each suggestion above except for the following elements: 

1. (Fixed a Bug) Since the advanced settings page was allowing the user too much flexibility in the app which in turn caused the AI to produce odd outputs. Therefore, Kevin and I thought best to remove it in this update and only keep the 3 mode AI settings page slider.
2. Optional extra feature: make the side bar collapsible to conserve space. I Didn't feel it was urgent enough to put off thoroughly testing the AI by having it create plenty of stories just to create a collapsible sidebar.
